name: arcticdb
channels:
  - conda-forge
dependencies:
  # Build tools
  - sel(win): ninja
  - wheel
  - setuptools
  - cxx-compiler
  - c-compiler
  - cmake
  - ccache
  - sccache
  - gtest
  - gflags
  - benchmark
  - doxygen
  - libboost-devel
  - liblzma-devel
  - grpcio
  - grpcio-tools
  - protobuf
  # Build dependencies
  - krb5
  - lz4-c
  - double-conversion
  - libevent
  # TODO: Fix builds for missing symbols.
  - libmongocxx <3.9
  - zstd
  - pybind11
  - pcre2
  - cyrus-sasl
  - aws-sdk-cpp >=1.11.405
  - prometheus-cpp
  - libprotobuf <7
  - openssl
  # TODO: Understand failures with 8.17
  - libcurl >=8.18
  - bitmagic
  - sparrow-devel==2.2.0
  - spdlog
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - fmt
  - folly==2025.04.14.00
  - unordered_dense
  - entt
  # Vendored build dependencies (see `cpp/thirdparty` and `cpp/vcpkg.json`)
  # Versions must be kept in sync
  - xxhash==0.8.2
  - semimap
  - rapidcheck
  - msgpack-c
  - recycle
  # Matches the version of lmdb as vendored in its submodule.
  - lmdb==0.9.22
  - lmdbxx
  - libiconv
  - aws-c-s3
  # Build dependencies for tests
  - libarrow
  # Python dependences
  - python >=3.12,<3.14
  - packaging
  - numpy
  - pandas <3
  - pytz
  - attrs
  - boto3
  - werkzeug
  - moto
  - mock
  # msgpack 0.5.0 is required for strict_types argument, needed for correct pickling fallback
  - msgpack-python >=0.5.0
  # Python dependencies (for tests only)
  # Pinned to avoid test disruption (in phase with the pin in setup.cfg)
  # See: https://github.com/man-group/ArcticDB/pull/291
  - hypothesis <6.73
  - pytest-sugar
  - pytest-timeout
  - azure-storage-blob
  - azure-identity
  - polars
  - pyarrow
  - asv
  - pymongo
  - pytest
  - retrying
  - trustme
  - psutil
  - pytest-xdist
  # Use memray and pytest-memray only on Linux and MacOS
  - sel(unix): memray
  - sel(unix): pytest-memray
