name: __ec2_runner
on:
  workflow_call:
    inputs:
      job_type:           {required: true, type: string, description: Selects the steps to enable}
      label:              {type: string, description: the label of the machine that was create by the start-runner job needed by the stop-runner job}
      ec2-instance-id:    {type: string, description: the ec2-instance-id of the machine that was create by the start-runner job needed by the stop-runner job}
      image-id:           {default: ami-0936679d3002e5be3, type: string, description: ID of the Amazon Image that should be used as a base for the runner}
      instance-type:      {default: m6i.4xlarge, type: string, description: Instace type that will be used to create the runner VM}
      subnet-id:          {default: subnet-04ee7771eea5d61d9, type: string, description: VPC Subnet to be used when creating the runner}
      security-group-id:  {default: sg-08bd5ce9b15ba4f4b, type: string, description: Security Group to be used when creating the runner}
    outputs:
      label:             
        value: ${{ jobs.start-runner.outputs.label }}
      ec2-instance-id:   
        value: ${{ jobs.start-runner.outputs.ec2-instance-id }}
jobs:
  start-runner:
    if: inputs.job_type == 'start'
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-22.04
    continue-on-error: true
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_S3_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_S3_SECRET_KEY }}"
          aws-region: "eu-west-1"
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.3.3
        with:
          mode: start
          github-token: ${{ secrets.ARCTICDB_TEST_PAT }}
          ec2-image-id: ${{ inputs.image-id }}
          ec2-instance-type: ${{ inputs.instance-type }}
          subnet-id: ${{ inputs.subnet-id }}
          security-group-id: ${{ inputs.security-group-id }}

  stop-runner:
    name: Stop self-hosted EC2 runner
    if: inputs.job_type == 'stop'
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_S3_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_S3_SECRET_KEY }}"
          aws-region: "eu-west-1"
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2.3.3
        with:
          mode: stop
          github-token: ${{ secrets.ARCTICDB_TEST_PAT }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}
        
if: false
